version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    depends_on:
      - api

  api:
    image: varxii/inventoryapi:latest
    ports:
      - "3000:8080"
    volumes:
      - ./api/data:/app/data 
