apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: sethfinal
  name: advfrontend-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: sethstar.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: advfrontend-service
            port:
              number: 3000