
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sethfinal
  name: starapi-deployment
  labels:
    app: starapi
spec:
  selector:
    matchLabels:
      app: starapi
  template:
    metadata:
      labels:
        app: starapi
    spec:
      containers:
      - name: starapi
        image: varxii/advapi:${RUN_ID} #;'odfsja;kljf'
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /data # Make sure the application reads/writes to this path
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: starapi-pvc # Updated to match PVC name

---
# Service
apiVersion: v1
kind: Service
metadata:
  namespace: sethfinal
  name: starapi-service
spec:
  type: ClusterIP
  selector:
    app: starapi
  ports:
    - port: 8080
      targetPort: 8080

---
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: starapi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/inventory # Path on the host machine

---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starapi-pvc # Match this name with Deployment
  namespace: sethfinal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: sethfinal
  name: starapi-ingress
spec:
  # tls:
  # - hosts:
  #   - fngauto.duckdns.org
  ingressClassName: nginx
  rules:
  - host: sethapi.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: starapi-service
            port:
              number: 8080

