
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sethfinal
  name: starsdatabase-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sethfinal
  name: starsdatabase-db-deployment
  labels:
    app: starsdatabase-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: starsdatabase-db
  template:
    metadata:
      labels:
        app: starsdatabase-db
    spec:
      containers:
      - name: starsdatabase-db
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: starsdatabase_db
        volumeMounts:
        - name: postgresstorage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgresstorage
        persistentVolumeClaim:
          claimName: starsdatabase-db-pvc
      - name: init-script
        configMap:
          name: starsdatabase-db-init
---
apiVersion: v1
kind: Service
metadata:
  namespace: sethfinal
  name: starsdatabase-db-service
spec:
  type: ClusterIP
  selector:
    app: starsdatabase-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: sethfinal
  name: starsdatabase-db-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS starsdatabase_user (
      id SERIAL PRIMARY KEY,
      first_name text,
      last_name text,
      phone text,
      email text,
      first_name_status text,
      last_name_status text,
      phone_status text,
      email_status text,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO starsdatabase_user (
      first_name, last_name, phone, email, first_name_status, last_name_status, phone_status, email_status
    ) VALUES
    ('John', 'Doe', '123-456-7890', 'john.doe@example.com', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE', 'WEB_VISIBLE'),
    ('Jane', 'Smith', '987-654-3210', 'jane.smith@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE', 'PRIVATE'),
    ('Alice', 'Johnson', '555-123-4567', 'alice.johnson@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE', 'WEB_VISIBLE'),
    ('Bob', 'Brown', '555-987-6543', 'bob.brown@example.com', 'WEB_VISIBLE', 'WEB_VISIBLE', 'WEB_VISIBLE', 'PRIVATE');