name: Deploy Vite React App and C# API
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Log into Docker"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Linting + Build Warnings"
        run: |
          echo "Running Lint Checks"
          cd client 
          npm install
          npm run check

      - name: "Testing"
        run: |
          echo "Running Tests"
          cd client
          npm run test

      - name: "Build and Push Docker RSBuild App image"
        run: |
          cd client
          docker build -t varxii/advfrontend:${{github.run_id}} -t varxii/advfrontend:latest .
          
          docker push varxii/advfrontend --all-tags

      - name: "Kubernetes Apply Configurations For the RSBuild App"
        run: |
          echo "Deploying RSBuild App"
          cd client
          export RUN_ID=${{github.run_id}}
          for file in ./kube/*; do
            echo "applying $file"
            cat $file | envsubst | kubectl apply -f -
          done

      - name: "Testing"
        run: |
          echo "Running Tests"
          cd client
          npm run test

      - name: "Deploy C# API"
        run: |
          echo "Deploying C# API"
          cd api
          dotnet format
          docker build -t varxii/advapi:${{github.run_id}} -t varxii/advapi:latest .
          docker push varxii/advapi --all-tags

      - name: "Kubernetes Apply Configurations For the C# API"
        run: |
          echo "Deploying C# API"
          cd api
          export RUN_ID=${{github.run_id}}
          for file in ./kube/*; do
            echo "applying $file"
            cat $file | envsubst | kubectl apply -f -
          done
